print('Please enter your Maths mark')
Math = int(input())
print('Please enter your Chemistry mark')
Chem = int(input())
print('Please enter your Physics mark')
Phys = int(input())
z = (int(Math)*int(Chem)*int(Phys)/100)

if z >= 70: print('A')
elif z >= 60: print('B')
elif z >= 50: print('C')
elif z >= 40: print('D')
else : print('You Failed')
